[package]
name = "raylib-hotreload-template"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
libloading = "0.8.3"
raylib-light = "0.0.1"
game = { path = "game" }

[[bin]]
name = "raylib-hotreload-template"
path = "main.rs"
